# https://api.hh.ru/openapi/redoc#tag/Obshie-spravochniki/paths/~1dictionaries/get
# This is not all!

SCHEDULE_REMOTE = "remote"

GENDER_MALE = "male"
GENDER_FEMALE = "female"

EXPERIENCE_NO = "noExperience"
EXPERIENCE_1_3_YEARS = "between1And3"
EXPERIENCE_3_6_YEARS = "between3And6"
EXPERIENCE_MORE_6_YEARS = "moreThan6"

EMPLOYMENT_FULL = "full"
EMPLOYMENT_PART = "part"
EMPLOYMENT_PROJECT = "project"
EMPLOYMENT_PROBATION = "probation"
EMPLOYMENT_VOLUNTEER = "volunteer"

CURRENCY_AZN = "AZN"
CURRENCY_EUR = "EUR"
CURRENCY_GEL = "GEL"
CURRENCY_KGS = "KGS"
CURRENCY_KZT = "KZT"
CURRENCY_RUR = "RUR"
CURRENCY_UAH = "UAH"
CURRENCY_USD = "USD"
CURRENCY_UZS = "UZS"

VACANCY_SEARCH_ORDER_PUBLICATION_TIME = "publication_time"
VACANCY_SEARCH_ORDER_SALARY_DESC = "salary_desc"
VACANCY_SEARCH_ORDER_SALARY_ASC = "salary_asc"
VACANCY_SEARCH_ORDER_RELEVANCE = "relevance"
VACANCY_SEARCH_ORDER_DISTANCE = "distance"

VACANCY_SEARCH_FIELD_NAME = "name"
VACANCY_SEARCH_FIELD_COMPANY_NAME = "company_name"
VACANCY_SEARCH_FIELD_DESCRIPTION = "description"

# Utils.
VACANCY_SEARCH_MAX_PER_PAGE = 100
